from tkinter import *
from PIL import ImageTk,Image
import sqlite3
root=Tk()
conn = sqlite3.connect('test1.db')
cursor=conn.cursor()
print("database has opened successfully");
print("Table has created.")
root.title("FOOD SERVICE:")
Font= ('monotype corsiva',15, 'bold')
l=Label(root,text="EMAIL ID :",font=Font,width='25',foreground="blue")
l1=Label(root,text="MOBILE NUMBER :",font=Font,width='25',foreground="blue")
l.place(x=500,y=50)
l1.place(x=500,y=90)
e=Entry(root,width="50")
e1=Entry(root,width="50")
e.place(x=750,y=50)
e1.place(x=750,y=90)
def insert():
    g=e.get()
    g1=e1.get()
    conn.execute('''insert into login_f(Email,Mobile)values (?,?)''',(g,g1))
    conn.commit()
    print("1 row inserted")
    e.delete(0,END)
    e1.delete(0,END)
bl=Button(root,text="store",font=Font,foreground="red",command=insert)
bl.place(x=860,y=130)
def clear():
    l.destroy()
    l1.destroy()
    e.destroy()
    e1.destroy()
    b.destroy()
    bl.destroy()
    labelfont=('monotype corsiva', 20, 'bold')
    ls=Label(root,text='Food Service Application ')
    ls.place(x=200,y=0)
    ls.config(bg='white', fg='brown')
    ls.config(font=labelfont)
    ls.config(height=3, width=20)
    root.config(bg="pink")
     
    def but1():
        l=Label(root,text="Hotel Name:",font=Font,width='25',bg="pink",foreground="blue")
        l1=Label(root,text="Address :",font=Font,width='25',bg="pink",foreground="blue")
        l.place(x=100,y=400)
        l1.place(x=100,y=450)
        e=Entry(root,width="50")
        e1=Entry(root,width="50")
        e.place(x=300,y=410)
        e1.place(x=300,y=460)
        e2=Entry(root,width="40")
        e2.place(x=400,y=510)
        e3=Entry(root,width="40")
        e3.place(x=400,y=560)
        def insert():
            g=e.get()
            g1=e1.get()
            conn.execute('''insert into veg_hotel(name,address)values (?,?)''',(g,g1))
            print("1 row inserted")
            e.delete(0,END)
            e1.delete(0,END)
            conn.commit()
        def show():
            s=conn.execute('''select * from veg_hotel''')
            options = set()
            rows=s.fetchall()
            for r in rows:
                print(r,end=" ")
                variable11 = StringVar(root)
                options.add(r)
                wn= OptionMenu(root, variable11, *options)
                wn.place(x=120,y=190)
            def img():
                i1=Image.open("veg-thali.jpg")
                i1=i1.resize((595,595),Image.ANTIALIAS)
                i=ImageTk.PhotoImage(i1)
                c.create_image(0,0,anchor=NW,image=i)
                c.i=i
                wn.destroy()
            b=Button(root,text="ok",font=Font,foreground="blue",command=img)
            b.place(x=210,y=130)
            conn.commit()
        def delete():
            g2=e2.get()
            s=cursor.execute('''delete from veg_hotel where name=?''',(g2,))
            rows=s.fetchall()
            for r in rows:
                print(r)
            print("one row has deleted successfully")
            conn.commit()
        def search():
            g3=e3.get()
            c=0
            s=cursor.execute('''select * from veg_hotel where name=?''',(g3,))
            e3.delete(0,END)
            rows=s.fetchall()
            for i in rows:
                if(i):
                    print(i)
                    c=c+1
                    print("one row has selected successfully",c)
                    l=Label(root,text=c,fg="blue",font=Font,width="2")
                    l.place(x=700,y=560)
                elif(i==False):
                    print("There is no veg hotel of this name.")
            conn.commit()
        b3=Button(root,text="search",font=Font,foreground="blue",command=search)
        b3.place(x=330,y=550)
        b2=Button(root,text="detete",font=Font,foreground="blue",command=delete)
        b2.place(x=330,y=500)
        b1=Button(root,text="details",font=Font,foreground="blue",command=show)
        b1.place(x=250,y=500)
        b=Button(root,text="insert",font=Font,foreground="blue",command=insert)
        b.place(x=180,y=500)
        c=Canvas(root,height="600",width="600",bg="pink")
        c.place(x=800,y=50)
        i1=Image.open("veg-hotel.jpg")
        i1=i1.resize((595,595),Image.ANTIALIAS)
        i=ImageTk.PhotoImage(i1)
        c.create_image(0,0,anchor=NW,image=i)
        c.i=i
        def clearall():
            b3.destroy()
            b2.destroy()
            b12.destroy()
            b1.destroy()
            c.destroy()
            b.destroy()
            l.destroy()
            l1.destroy()
            e.destroy()
            e1.destroy()
            e2.destroy()
            e3.destroy()
            b11.destroy()
            b111.destroy()
            font1= ('monotype corsiva',60, 'bold')
            font2= ('monotype corsiva',20, 'bold')
            lsh=Label(root,text="Add Your Favourite Food",bg="pink",font=font1,width="200")
            lsh.pack()
            lsh1=Label(root,text="Insert Food From Here:",bg="pink",font=font2,foreground="blue")
            lsh1.place(x=10,y=100)
            ec=Entry(root,width="30")
            ec.place(x=300,y=105)
     
            c2=Canvas(root,height="600",width="600",bg="pink")
            c2.place(x=850,y=100)
            i1=Image.open("Punjabi dish.jpg")
            i1=i1.resize((600,600),Image.ANTIALIAS)
            i=ImageTk.PhotoImage(i1)
            c2.create_image(0,0,anchor=NW,image=i)
            c2.i=i
            def choose():
                gc=ec.get()
                conn.execute('''insert into food_insert11(name)values (?)''',(gc,))
                ec.delete(0,END)
                print("1 row inserted")
                conn.commit()
            def show1():
                s=conn.execute('''select * from food_insert11''')
                options = set()
                rows=s.fetchall()
                for r in rows:
                    print(r,end=" ")
                    variable11 = StringVar(root)
                    options.add(r)
                    wn= OptionMenu(root, variable11, *options)
                    wn.place(x=510,y=105)
                def img():
                    wn.destroy()
                    b.destroy()
                b=Button(root,text="ok",font=Font,foreground="blue",command=img)
                b.place(x=650,y=105)
                conn.commit()
            def allclear():
                lsh1.destroy()
                ec.destroy()
                bc.destroy()
                bc1.destroy()
                bc2.destroy()
                c2.destroy()
                lsh.destroy()
              
                lshc=Label(root,text="Choose Your Favourite Food",bg="pink",font=font1,width="200")
                lshc.pack()
                lsh1c=Label(root,text="Select Food From Here:",bg="pink",font=font2,foreground="blue")
                lsh1c.place(x=10,y=100)
                OPTIONS = ["Veg Punjabi Dishes","Starters","Soups","Rice","Noodles","Cold drinks","Ice cream","Sweets","Shaker"]
                variable11 = StringVar(root)
                wn= OptionMenu(root, variable11, *OPTIONS)
                wn.place(x=270,y=105)
                def msg3(*args):
               
                    t=variable11.get()
                    c1=Canvas(root,height="600",width="500",bg="white")
                    c1.place(x=400,y=100)
                    c2=Canvas(root,height="600",width="600",bg="pink")
                    c2.place(x=850,y=100)
                    font2= ('monotype corsiva',15, 'bold')
                    font3= ('monotype corsiva',8, 'bold')
                    lsh2=Label(root,text="orders",foreground="blue",font=font2)
                    lsh2.place(x=550,y=100)
                    lsh3=Label(root,text="Confirm",foreground="blue",font=font2)
                    lsh3.place(x=650,y=100)
                    lsh5=Label(root,text="Price",foreground="blue",font=font2)
                    lsh5.place(x=750,y=100)
                    def colddrinks():
                       lsh4=Label(root,text="Cold Coffee:",font=font2)
                       lsh4.place(x=410,y=150)
                       esh=Entry(root,width="5")
                       esh.place(x=550,y=150)
                       lsh7=Label(root,text="Cold Cola:",font=font2)
                       lsh7.place(x=410,y=180)
                       esh1=Entry(root,width="5")
                       esh1.place(x=550,y=180)
                       def o():
                           t1=esh.get()
                           con=int(t1)
                           conn.execute('''insert into food_store1(name,price)values ('Cold Coffee',40)''')
                           print("1 row inserted")
                           lsh6=Label(root,text=con*40)
                           lsh6.place(x=750,y=150)
                           i1=Image.open("cold coffe.jpg")
                           i1=i1.resize((600,600),Image.ANTIALIAS)
                           i=ImageTk.PhotoImage(i1)
                           c2.create_image(0,0,anchor=NW,image=i)
                           c2.i=i
                       def o1():
                           t2=esh1.get()
                           con1=int(t2)
                           conn.execute('''insert into food_store1(name,price)values ('cold-cola',25)''')
                           print("1 row inserted")
                           lsh8=Label(root,text=con1*25)
                           lsh8.place(x=750,y=180)
                           i1=Image.open("cold-cola.jpg")
                           i1=i1.resize((600,600),Image.ANTIALIAS)
                           i=ImageTk.PhotoImage(i1)
                           c2.create_image(0,0,anchor=NW,image=i)
                           c2.i=i
                       bsh1=Button(root,text="ok",command=o1)
                       bsh1.place(x=650,y=180)
                       bsh=Button(root,text="ok",command=o)
                       bsh.place(x=650,y=150)
                    if(t=="Veg Punjabi Dishes"):
                        Panjabi()
                    elif(t=="Cold drinks"):
                        colddrinks()
                variable11.trace('w',msg3)
            bc=Button(root,text="insert",font=Font,foreground="blue",command=choose)
            bc.place(x=250,y=135)
            bc1=Button(root,text="details",font=Font,foreground="blue",command=show1)
            bc1.place(x=350,y=135)
            bc2=Button(root,text="Confirm",font=Font,foreground="blue",command=allclear)
            bc2.place(x=450,y=135)
        
        b111=Button(root,text="Confirm Hotel",command=clearall)
        b111.place(x=340,y=650)
    b11=Button(root,text="Vegeterian",command=but1)
    b11.place(x=120,y=130)
    b11.config(height=3, width=10)
    def but2():
        l=Label(root,text="Hotel Name:",font=Font,width='25',bg="pink",foreground="blue")
        l1=Label(root,text="Address :",font=Font,width='25',bg="pink",foreground="blue")
        l.place(x=100,y=400)
        l1.place(x=100,y=450)
        e=Entry(root,width="50")
        e1=Entry(root,width="50")
        e.place(x=300,y=410)
        e1.place(x=300,y=460)
        e2=Entry(root,width="40")
        e2.place(x=400,y=510)
        e3=Entry(root,width="40")
        e3.place(x=400,y=560)
        def insert():
            g=e.get()
            g1=e1.get()
            conn.execute('''insert into nonveg_hotel(name,address)values (?,?)''',(g,g1))
            print("1 row inserted")
            e.delete(0,END)
            e1.delete(0,END)
            conn.commit()
        def show():
            s=conn.execute('''select * from nonveg_hotel''')
            options = set()
            rows=s.fetchall()
            for r in rows:
                print(r,end=" ")
                variable11 = StringVar(root)
                options.add(r)
                wn= OptionMenu(root, variable11, *options)
                wn.place(x=510,y=190)
            def img():
                i1=Image.open("nonveg.jpg")
                i1=i1.resize((595,595),Image.ANTIALIAS)
                i=ImageTk.PhotoImage(i1)
                c.create_image(0,0,anchor=NW,image=i)
                c.i=i
                wn.destroy()
            b=Button(root,text="ok",font=Font,foreground="blue",command=img)
            b.place(x=650,y=130)
            conn.commit()
        def delete():
            g2=e2.get()
            s=cursor.execute('''delete from nonveg_hotel where name=?''',(g2,))
            rows=s.fetchall()
            for r in rows:
                print(r)
            print("one row has deleted successfully")
            conn.commit()
        def search():
            g3=e3.get()
            c=0
            s=cursor.execute('''select * from nonveg_hotel where name=?''',(g3,))
            e3.delete(0,END)
            rows=s.fetchall()
            for i in rows:
                if(i):
                    print(i)
                    c=c+1
                    print("one row has selected successfully",c)
                    l=Label(root,text=c,fg="blue",font=Font,width="2")
                    l.place(x=700,y=560)
                elif(i==False):
                    print("There is no nonveg hotel of this name.")
            conn.commit()
        b3=Button(root,text="search",font=Font,foreground="blue",command=search)
        b3.place(x=330,y=550)
        b2=Button(root,text="detete",font=Font,foreground="blue",command=delete)
        b2.place(x=330,y=500)
        b1=Button(root,text="details",font=Font,foreground="blue",command=show)
        b1.place(x=250,y=500)
        b=Button(root,text="insert",font=Font,foreground="blue",command=insert)
        b.place(x=180,y=500)
        c=Canvas(root,height="600",width="600",bg="pink")
        c.place(x=800,y=50)
        i1=Image.open("nonveg-hotel1.jpg")
        i1=i1.resize((595,595),Image.ANTIALIAS)
        i=ImageTk.PhotoImage(i1)
        c.create_image(0,0,anchor=NW,image=i)
        c.i=i
        def clearall():
            b3.destroy()
            b2.destroy()
            b12.destroy()
            b1.destroy()
            c.destroy()
            b.destroy()
            l.destroy()
            l1.destroy()
            e.destroy()
            e1.destroy()
            e2.destroy()
            e3.destroy()
            b11.destroy()
            b111.destroy()
            font1= ('monotype corsiva',60, 'bold')
            font2= ('monotype corsiva',20, 'bold')
            lsh=Label(root,text="Choose Your Favourite Food",bg="pink",font=font1,width="200")
            lsh.pack()
            lsh1=Label(root,text="Insert Food From Here:",bg="pink",font=font2,foreground="blue")
            lsh1.place(x=10,y=100)
            ec=Entry(root,width="30")
            ec.place(x=300,y=105)
            c2=Canvas(root,height="600",width="600",bg="pink")
            c2.place(x=850,y=100)
            i1=Image.open("nonveg.jpg")
            i1=i1.resize((600,600),Image.ANTIALIAS)
            i=ImageTk.PhotoImage(i1)
            c2.create_image(0,0,anchor=NW,image=i)
            c2.i=i
            
   
                gc=ec.get()
                conn.execute('''insert into food_insert1(name)values (?)''',(gc,))
                ec.delete(0,END)
                print("1 row inserted")
                conn.commit()
            def show1():
                s=conn.execute('''select * from food_insert1''')
                options = set()
                rows=s.fetchall()
                for r in rows:
                    print(r,end=" ")
                    variable11 = StringVar(root)
                    options.add(r)
                    wn= OptionMenu(root, variable11, *options)
                    wn.place(x=510,y=105)
                    conn.commit()
                def img():
                    wn.destroy()
                    b.destroy()
                b=Button(root,text="ok",font=Font,foreground="blue",command=img)
                b.place(x=600,y=130)
            def allclear():
                lsh1.destroy()
                ec.destroy()
                bc.destroy()
                bc1.destroy()
                bc2.destroy()
                 
            bc=Button(root,text="insert",font=Font,foreground="blue",command=choose)
            bc.place(x=250,y=135)
            bc1=Button(root,text="details",font=Font,foreground="blue",command=show1)
            bc1.place(x=350,y=135)
            bc2=Button(root,text="confirm",font=Font,foreground="blue",command=allclear)
            bc2.place(x=450,y=135)
        b111=Button(root,text="Confirm Hotel",command=clearall)
        b111.place(x=340,y=650)
    b12=Button(root,text="Non-Vegeterian",command=but2)
    b12.place(x=500,y=130)
    b12.config(height=3, width=12)
b=Button(root,text="login",font=Font,foreground="red",command=clear)
b.place(x=750,y=130)
root.mainloop()

